### ISSUE TITLE
Та же проблема.

### ISSUE THREAD

**Issue by DarkSufferose** [ImMALWARE/bash-warp-generator#10]
Подскажите пожалуйста, на убунте скрипт не работает?

**Comment by ImMALWARE** [comment]
на своей локальной машине не надо его выполнять, потому что запросы для получения конфига заблокированы ркн
Попробуйте выполнить на https://terminator.aeza.net/en. Нужно выбрать Debian. Затем выполнить 
```apt install sudo```
Затем ```curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash```

**Comment by DarkSufferose** [comment]
У меня куплена впс за границей, но там есть свой софт, и оно на бубунте.
Необходимо все таки ставить дебиан?

**Comment by Dorlander** [comment]
Установка зависимостей...
Get:1 https://repo.mysql.com/apt/debian bullseye InRelease [22.7 kB]
Hit:2 http://deb.debian.org/debian bullseye InRelease                                                                                                                                                                                             
Hit:3 https://apt.releases.hashicorp.com bullseye InRelease                                                                                                                                                                                       
Hit:4 https://download.docker.com/linux/debian bullseye InRelease                                                                                                                                                                                 
Hit:5 http://deb.debian.org/debian-security bullseye-security InRelease                                                                                                                                                                           
Hit:6 http://deb.debian.org/debian bullseye-updates InRelease                                                                                                                                                                              
Get:7 https://packages.sury.org/php bullseye InRelease [7,551 B]                                                                                                                                                     
Hit:8 https://packages.microsoft.com/debian/11/prod bullseye InRelease                                                                                                                                               
Get:9 https://packages.cloud.google.com/apt gcsfuse-bullseye InRelease [1,239 B]                                                                                     
Get:10 https://cli.github.com/packages bullseye InRelease [3,921 B]                                                                                       
Err:1 https://repo.mysql.com/apt/debian bullseye InRelease                                                             
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
Hit:11 https://packages.cloud.google.com/apt cloud-sdk-bullseye InRelease                                              
Hit:12 https://apt.llvm.org/bullseye llvm-toolchain-bullseye-13 InRelease                                              
Hit:13 https://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease

########## НАЧАЛО КОНФИГА ##########
[Interface]
PrivateKey = 
S1 = 0
S2 = 0
Jc = 120
Jmin = 23
Jmax = 911
H1 = 1
H2 = 2
H3 = 3
H4 = 4
Address = null, null
DNS = 1.1.1.1, 2606:4700:4700::1111, 1.0.0.1, 2606:4700:4700::1001

[Peer]
PublicKey = null
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = null:null
########### КОНЕЦ КОНФИГА ###########

**Comment by DarkSufferose** [comment]
> Установка зависимостей... Get:1 https://repo.mysql.com/apt/debian bullseye InRelease [22.7 kB] Hit:2 http://deb.debian.org/debian bullseye InRelease Hit:3 https://apt.releases.hashicorp.com bullseye InRelease Hit:4 https://download.docker.com/linux/debian bullseye InRelease Hit:5 http://deb.debian.org/debian-security bullseye-security InRelease Hit:6 http://deb.debian.org/debian bullseye-updates InRelease Get:7 https://packages.sury.org/php bullseye InRelease [7,551 B] Hit:8 https://packages.microsoft.com/debian/11/prod bullseye InRelease Get:9 https://packages.cloud.google.com/apt gcsfuse-bullseye InRelease [1,239 B] Get:10 https://cli.github.com/packages bullseye InRelease [3,921 B] Err:1 https://repo.mysql.com/apt/debian bullseye InRelease The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C Hit:11 https://packages.cloud.google.com/apt cloud-sdk-bullseye InRelease Hit:12 https://apt.llvm.org/bullseye llvm-toolchain-bullseye-13 InRelease Hit:13 https://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease
> 
> ########## НАЧАЛО КОНФИГА ########## [Interface] PrivateKey = S1 = 0 S2 = 0 Jc = 120 Jmin = 23 Jmax = 911 H1 = 1 H2 = 2 H3 = 3 H4 = 4 Address = null, null DNS = 1.1.1.1, 2606:4700:4700::1111, 1.0.0.1, 2606:4700:4700::1001
> 
> [Peer] PublicKey = null AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = null:null ########### КОНЕЦ КОНФИГА ###########

?

**Comment by Dorlander** [comment]
нет ключа, печально вот что

**Comment by DarkSufferose** [comment]
а, да мб позже заработает, народу хлынуло много

**Comment by splite03** [comment]
на терминаторе очередь большая, но работает, как часы, все зависимости подтягиваются и конфиг собирает ровно

**Comment by ImMALWARE** [comment]
Закрою пока этот issue, оставлю открытым только один по этому поводу - #8 
1 вариант: Попытайтесь дождаться google cloud shell.
2 вариант: Попробуйте выполнить на https://terminator.aeza.net/en. Нужно выбрать Debian. Затем выполнить
```apt install sudo```
Затем ```curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash```
3 вариант: https://github.com/codespaces 
![image](https://github.com/user-attachments/assets/05ea4857-2937-4098-a271-b4f8f3690d28)
Если нашли ещё варианты, пишите в #8
